version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        # volumes:
        #     - ./postgres/pg_data:/pg_data/
    mydb:
        image: postgres:11.6
        environment:
            - POSTGRES_USER=mydb
            - POSTGRES_PASSWORD=mydb
            - POSTGRES_DB=mydb
        ports:
            - "5439:5432"
        volumes:
            - ./postgres/pg_data:/pg_data/

    webserver:
        image: puckel/docker-airflow:1.10.6
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=y
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags/
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=db
        volumes:
            - ./data:/var/lib/mysql/
            - ./config/my.cnf:/etc/mysql/my.cnf
            - ./imported_data:/imported_data/

        ports:
            - "3306:3306"
            - "33060:33060"
        expose:
             - "3306"
             - "33060"
        # command: mysqld --default-authentication-plugin=mysql_native_password
        # command: --default-authentication-plugin=mysql_native_password
        restart: always

